### PR TITLE
[61] change AddEcoNewsDtoRequest model

### LINKED ISSUE #61: [Eco-News, POST/econews] The "addEcoNewsDtoRequest" form-data model has to be updated
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is not logged in

**Steps to reproduce**
1. Select the “Eco-news" controller.
2. Select the method POST/econews.
3. Pay attention to the "addEcoNewsDtoRequest" form-data model.

**Actual result:** 
The "addEcoNewsDtoRequest" form-data model:

{
  "image": "string",
  "source": "https://example.org/",
  "shortInfo": "string",
  "tags": [
    "string"
  ],
  "titleTranslation":
     {"content": "string",
     "languageCode": "string"},
  "textTranslation":
     {"content": "string",
     "languageCode": "string"}
}

**Expected result:** 
The "addEcoNewsDtoRequest" form data model:

{"tags":["string"],"text":"string","title":"string","source":"string"}

### PR DESCRIPTION
**Pull request by SaenkoVova**
## Summary by CodeRabbit

- **Bug Fixes**
  - Removed support for the "image" and "shortInfo" fields in EcoNews creation requests.
  - Simplified the structure of example JSON for EcoNews API documentation.
- **Tests**
  - Updated tests to align with the removal of "image" and "shortInfo" fields from EcoNews requests.
- **Documentation**
  - Updated API example responses to reflect the new, simplified EcoNews request structure.

### CODE REVIEW

File: core/src/main/java/greencity/constant/SwaggerExampleModel.java [hunk 1]
```diff
@@ -15,18 +15,13 @@ public final class SwaggerExampleModel {
         + "\t<pre>\n";
 
     private static final String EXAMPLE =
```
Comment (RostyslavZadyraichuk) [inline core/src/main/java/greencity/constant/SwaggerExampleModel.java:17]: In this case it's acceptable, because we also have task for UpdateEcoNewsDtoRequest class, but in general case it may cause problems, becuase EXAMPLE constant is also used as part of UPDATE_ECO_NEWS constant, that has different structure.

File: service/src/test/java/greencity/service/EcoNewsServiceImplTest.java [hunk 2]
```diff
@@ -107,8 +107,8 @@ void save() throws MalformedURLException {
     @Test
     void saveWithExistedImage() throws IOException {
```
Comment (RostyslavZadyraichuk) [inline service/src/test/java/greencity/service/EcoNewsServiceImplTest.java:108]: I think that test case isn't relevant anymore, so you can comment/remove it fully.

**Review by RostyslavZadyraichuk — APPROVED** [review]

**Review by dimasowner — APPROVED** [review]

**Review by Kirasin225 — APPROVED** [review]
